<a href="https://colab.research.google.com/github/OTD-Aregbesola/Obesity_Prediction/blob/main/Obesity_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction

This dataset include data for the estimation of obesity levels in individuals from the countries of Mexico, Peru and Colombia, based on their eating habits and physical condition.

The data contains 17 attributes and 2111 records, the records are labeled with the class variable NObesity (Obesity Level), that allows classification of the data using the values of Insufficient Weight, Normal Weight, Overweight Level I, Overweight Level II, Obesity Type I, Obesity Type II and Obesity Type III.


Data Details

Gender: Gender

Age: Age

Height : in metres

Weight : in kgs

family_history : Has a family member suffered or suffers from overweight?

FAVC : Do you eat high caloric food frequently?

FCVC : Do you usually eat vegetables in your meals?

NCP : How many main meals do you have daily?

CAEC : Do you eat any food between meals?

SMOKE : Do you smoke?

CH2O : How much water do you drink daily?

SCC : Do you monitor the calories you eat daily?

FAF: How often do you have physical activity?

TUE : How much time do you use technological devices such as cell phone, videogames, television, computer and others?

CALC : How often do you drink alcohol?

MTRANS : Which transportation do you usually use?

Obesity_level (Target Column) : Obesity level

https://www.semanticscholar.org/paper/Dataset-for-estimation-of-obesity-levels-based-on-Palechor-Manotas/35b40bacd2ffa9370885b7a3004d88995fd1d011

#Data Wrangling and Importation core libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv('/content/Obesity prediction.csv')

df.head()

Gender   Age  Height  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  \
0    no   2.0   no  0.0  1.0          no  Public_Transportation   
1   yes   3.0  yes  3.0  0.0   Sometimes  Public_Transportation   
2    no   2.0   no  2.0  1.0  Frequently  Public_Transportation   
3    no   2.0   no  2.0  0.0  Frequently                Walking   
4    no   2.0   no  0.0  0.0   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overweight_Level_II

In [ ]:
df.describe(include ='number').T

count       mean        std    min        25%        50%         75%  \
Age     2111.0  24.312600   6.345968  14.00  19.947192  22.777890   26.000000   
Height  2111.0   1.701677   0.093305   1.45   1.630000   1.700499    1.768464   
Weight  2111.0  86.586058  26.191172  39.00  65.473343  83.000000  107.430682   
FCVC    2111.0   2.419043   0.533927   1.00   2.000000   2.385502    3.000000   
NCP     2111.0   2.685628   0.778039   1.00   2.658738   3.000000    3.000000   
CH2O    2111.0   2.008011   0.612953   1.00   1.584812   2.000000    2.477420   
FAF     2111.0   1.010298   0.850592   0.00   0.124505   1.000000    1.666678   
TUE     2111.0   0.657866   0.608927   0.00   0.000000   0.625350    1.000000   

           max  
Age      61.00  
Height    1.98  
Weight  173.00  
FCVC      3.00  
NCP       4.00  
CH2O      3.00  
FAF       3.00  
TUE       2.00

In [ ]:
df.describe(include ='object').T

count unique                    top  freq
Gender          2111      2                   Male  1068
family_history  2111      2                    yes  1726
FAVC            2111      2                    yes  1866
CAEC            2111      4              Sometimes  1765
SMOKE           2111      2                     no  2067
SCC             2111      2                     no  2015
CALC            2111      4              Sometimes  1401
MTRANS          2111      5  Public_Transportation  1580
Obesity         2111      7         Obesity_Type_I   351

Key Insight



*   FCVC columns seems like an open ended question that ought to contain a binary input but we have multiple input in our data.
*   There's a need to change the column names to make it reflect the question more correct.


*   There's no null values
*   We are not dropping the duplicate value because there's no unique identifier to distinguish the data, it mighty be a different person information






#Data Cleaning



*   Investigate the FCVC columns closely
*   Change the name of certain column



In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          2111 non-null   object 
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object 
 5   FAVC            2111 non-null   object 
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object 
 9   SMOKE           2111 non-null   object 
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object 
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object 
 15  MTRANS          2111 non-null   object 
 16  Obesity         2111 non-null   object 
dtypes: float64(8), object(9)
memory u

In [ ]:
df.isnull().sum()

Gender            0
Age               0
Height            0
Weight            0
family_history    0
FAVC              0
FCVC              0
NCP               0
CAEC              0
SMOKE             0
CH2O              0
SCC               0
FAF               0
TUE               0
CALC              0
MTRANS            0
Obesity           0
dtype: int64

In [ ]:
df.duplicated().sum()

24

In [ ]:
df['FCVC'].value_counts()

FCVC
3.000000    652
2.000000    600
1.000000     33
2.823179      2
2.214980      2
           ... 
2.927409      1
2.706134      1
2.010684      1
2.300408      1
2.680375      1
Name: count, Length: 810, dtype: int64

In [ ]:
df_copy = df.copy()

Upon investigation we discover that the column contain decimal data type and so we couldn't figure out , what insight the column might be passing

In [ ]:
df_copy.drop('FCVC', axis= 1, inplace= True)

We also discover, changing the names will affect our introduction and so we will change the name to lowercase for uniformity sake.


In [ ]:
df_copy.columns = df_copy.columns.str.lower()

df_copy.head()

gender   age  height  weight family_history favc  ncp       caec smoke  \
0  Female  21.0    1.62    64.0            yes   no  3.0  Sometimes    no   
1  Female  21.0    1.52    56.0            yes   no  3.0  Sometimes   yes   
2    Male  23.0    1.80    77.0            yes   no  3.0  Sometimes    no   
3    Male  27.0    1.80    87.0             no   no  3.0  Sometimes    no   
4    Male  22.0    1.78    89.8             no   no  1.0  Sometimes    no   

   ch2o  scc  faf  tue        calc                 mtrans              obesity  
0   2.0   no  0.0  1.0          no  Public_Transportation        Normal_Weight  
1   3.0  yes  3.0  0.0   Sometimes  Public_Transportation        Normal_Weight  
2   2.0   no  2.0  1.0  Frequently  Public_Transportation        Normal_Weight  
3   2.0   no  2.0  0.0  Frequently                Walking   Overweight_Level_I  
4   2.0   no  0.0  0.0   Sometimes  Public_Transportation  Overweight_Level_II

#Data Preprocessing

In [ ]:
def data_preprocessing(data):
  df_new = df_copy.copy()
  #encode the categorical variable
  le = LabelEncoder()
  cat_col = df_new.select_dtypes(include= 'object').columns
  for col in cat_col:
    df_new[col] = le.fit_transform(df_new[col])
  #separate the independent and dependent variable
  y = df_new['obesity']
  X = df_new.drop('obesity', axis = 1)

  #split the data
  X_train, X_test, y_train, y_test = train_test_split (X,y, test_size = 0.20, random_state = 42)

  #scalling the data
  scaler = StandardScaler()
  X_train_scale = scaler.fit_transform(X_train)
  X_test_scale = scaler.transform(X_test)



  return X_train_scale, X_test_scale, y_train, y_test, scaler

In [ ]:
X_train_scale, X_test_scale, y_train, y_test, scaler = data_preprocessing(df_copy)

In [ ]:
print('X_train_scale:', X_train_scale.shape)
print('X_test_scale:', X_test_scale.shape)
print('y_train:', y_train.shape)
print('y_test', y_test.shape)

X_train_scale: (1688, 15)
X_test_scale: (423, 15)
y_train: (1688,)
y_test (423,)


#Logistic Regression

In [ ]:
model = LogisticRegression(multi_class= 'multinomial', solver = 'lbfgs', max_iter= 1000)
model.fit(X_train_scale, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='multinomial')

In [ ]:
#prediction
y_pred = model.predict(X_test_scale)

#Evaluation
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.84      1.00      0.91        56
           1       0.90      0.61      0.73        62
           2       0.96      0.87      0.91        78
           3       0.92      0.98      0.95        58
           4       0.97      1.00      0.98        63
           5       0.75      0.79      0.77        56
           6       0.74      0.84      0.79        50

    accuracy                           0.87       423
   macro avg       0.87      0.87      0.86       423
weighted avg       0.88      0.87      0.87       423

Confusion Matrix:
 [[56  0  0  0  0  0  0]
 [11 38  0  0  0  9  4]
 [ 0  0 68  5  2  0  3]
 [ 0  0  1 57  0  0  0]
 [ 0  0  0  0 63  0  0]
 [ 0  4  0  0  0 44  8]
 [ 0  0  2  0  0  6 42]]
